//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TestProject.NWind
{

    [NonPersistent]
    public partial class SalesTotalsByAmount : XPLiteObject
    {
        decimal? fSaleamount;
        [Persistent(@"SaleAmount")]
        public decimal? Saleamount
        {
            get { return fSaleamount; }
            set { SetPropertyValue<decimal?>(nameof(Saleamount), ref fSaleamount, value); }
        }
        int fOrderid;
        [Persistent(@"OrderID")]
        public int Orderid
        {
            get { return fOrderid; }
            set { SetPropertyValue<int>(nameof(Orderid), ref fOrderid, value); }
        }
        string fCompanyname;
        [Size(40)]
        [Persistent(@"CompanyName")]
        [Nullable(false)]
        public string Companyname
        {
            get { return fCompanyname; }
            set { SetPropertyValue<string>(nameof(Companyname), ref fCompanyname, value); }
        }
        DateTime? fShippeddate;
        [Persistent(@"ShippedDate")]
        public DateTime? Shippeddate
        {
            get { return fShippeddate; }
            set { SetPropertyValue<DateTime?>(nameof(Shippeddate), ref fShippeddate, value); }
        }
    }

}
